export const PLP = [
  {
    id: 1,
    name: "Classic Tote",
    description: "Elegant, Durable, Spacious",
    price: "4,500.00",
    discountedPrice: "3,500.00",
    discountPercent: 22,
    color: "Black",
    finish: "Matte",
  },
  {
    id: 2,
    name: "Vintage Satchel",
    description: "Stylish, Compact, Versatile",
    price: "5,200.00",
    discountedPrice: "3,900.00",
    discountPercent: 25,
    color: "Olive Green",
    finish: "Leather",
  },
  {
    id: 3,
    name: "Urban Backpack",
    description: "Trendy, Lightweight, Durable",
    price: "3,200.00",
    discountedPrice: "2,400.00",
    discountPercent: 30,
    color: "Black",
    finish: "Matte",
  },
  {
    id: 4,
    name: "Leather Sling",
    description: "Premium, Sleek, Handy",
    price: "5,800.00",
    discountedPrice: "4,600.00",
    discountPercent: 20,
    color: "Olive Green",
    finish: "Leather",
  },
  {
    id: 5,
    name: "Travel Duffle",
    description: "Spacious, Sturdy, Waterproof",
    price: "7,000.00",
    discountedPrice: "5,600.00",
    discountPercent: 20,
    color: "Olive Green",
    finish: "Leather",
  },
  {
    id: 6,
    name: "Canvas Messenger",
    description: "Casual, Functional, Comfortable",
    price: "3,800.00",
    discountedPrice: "2,900.00",
    discountPercent: 24,
    color: "Black",
    finish: "Matte",
  },
  {
    id: 7,
    name: "Classic Tote",
    description: "Elegant, Durable, Spacious",
    price: "4,500.00",
    discountedPrice: "3,500.00",
    discountPercent: 22,
    color: "Black",
    finish: "Matte",
  },
  {
    id: 8,
    name: "Vintage Satchel",
    description: "Stylish, Compact, Versatile",
    price: "5,200.00",
    discountedPrice: "3,900.00",
    discountPercent: 25,
    color: "Brown",
    finish: "Glossy",
  },
  {
    id: 9,
    name: "Urban Backpack",
    description: "Trendy, Lightweight, Durable",
    price: "3,200.00",
    discountedPrice: "2,400.00",
    discountPercent: 30,
    color: "Brown",
    finish: "Glossy",
  },
  {
    id: 10,
    name: "Leather Sling",
    description: "Premium, Sleek, Handy",
    price: "5,800.00",
    discountedPrice: "4,600.00",
    discountPercent: 20,
    color: "Olive Green",
    finish: "Leather",
  },
  {
    id: 11,
    name: "Travel Duffle",
    description: "Spacious, Sturdy, Waterproof",
    price: "7,000.00",
    discountedPrice: "5,600.00",
    discountPercent: 20,
    color: "Brown",
    finish: "Glossy",
  },
  {
    id: 12,
    name: "Canvas Messenger",
    description: "Casual, Functional, Comfortable",
    price: "3,800.00",
    discountedPrice: "2,900.00",
    discountPercent: 24,
    color: "Black",
    finish: "Matte",
  },
];